## Convolutional Neural Networks (CNNs)

In [3]:
import torch
import torch.nn.functional as F

### Convolution operator - OOP way

**OOP - Based (torcn.nn)**
- in_channels : number of channels in input
- out_channels : number of output channels produced by convolution
- kernel_size : size of convolution kernel
- stride : stride of convolution. Default 1
- padding : padding of convolution. Zero padding

In [2]:
# Create 10 random images of shape (1, 28, 28)
images = torch.rand(10, 1, 28, 28)

# Build 6 conv. filters
conv_filters = torch.nn.Conv2d(in_channels=1, out_channels=6, kernel_size=3, stride=1, padding=1)

# Convolve the image with the filters 
output_feature = conv_filters(images)
print(output_feature.shape)

torch.Size([10, 6, 28, 28])


### Convolution operator - Functional way

**Functional - Based (torcn.nn.functional)**
- input : input tensor of shape (batch,in_channels,Height,Width)
- weights : filter of shape
- stride : the stride of the convolution kernel. Can be a single number or a tuple (sH,sW)
- padding : implicit zero padding on both sides of the input. Default 0

In [4]:
# Create 10 random images
image = torch.rand(10, 1, 28, 28)

# Create 6 filters
filters = torch.rand(6, 1, 3, 3)

# Convolve the image with the filters
output_feature = F.conv2d(image, filters, stride=1, padding=1)
print(output_feature.shape)

torch.Size([10, 6, 28, 28])


### Max-pooling operator

In [6]:
im = torch.tensor([[[[ 8.,  1.,  2.,  5.,  3.,  1.],
                    [ 6.,  0.,  0., -5.,  7.,  9.],
                    [ 1.,  9., -1., -2.,  2.,  6.],
                    [ 0.,  4.,  2., -3.,  4.,  3.],
                    [ 2., -1.,  4., -1., -2.,  3.],
                    [ 2., -4.,  5.,  9., -7.,  8.]]]])

# Build a pooling operator with size `2`.
max_pooling = torch.nn.MaxPool2d(2)

# Apply the pooling operator
output_feature = max_pooling(im) # OOP - BASED

# Use pooling operator in the image
output_feature_F = F.max_pool2d(im,2) # Functional - BASED

# print the results of both cases
print(output_feature)
print(output_feature_F)

tensor([[[[8., 5., 9.],
          [9., 2., 6.],
          [2., 9., 8.]]]])
tensor([[[[8., 5., 9.],
          [9., 2., 6.],
          [2., 9., 8.]]]])


### Average-pooling operator

In [8]:
# Build a pooling operator with size `2`.
avg_pooling = torch.nn.AvgPool2d(2)

# Apply the pooling operator
output_feature = avg_pooling(im)

# Use pooling operator in the image
output_feature_F = F.avg_pool2d(im, 2)

# print the results of both cases
print("OOP - Based")
print(output_feature)
print("\nFunctional - Based")
print(output_feature_F)

OOP - Based
tensor([[[[ 3.7500,  0.5000,  5.0000],
          [ 3.5000, -1.0000,  3.7500],
          [-0.2500,  4.2500,  0.5000]]]])

Functional - Based
tensor([[[[ 3.7500,  0.5000,  5.0000],
          [ 3.5000, -1.0000,  3.7500],
          [-0.2500,  4.2500,  0.5000]]]])
