## Introduction to PyTorch

In [1]:
# Import torch
import torch

### Creating tensors in PyTorch

In [2]:
# Create random tensor of size 3 by 3
your_first_tensor = torch.rand(3, 3)

# Calculate the shape of the tensor
tensor_size = your_first_tensor.size()

# Print the values of the tensor and its shape
print(your_first_tensor)
print(tensor_size)

tensor([[0.7117, 0.2616, 0.8411],
        [0.5533, 0.1551, 0.0745],
        [0.6653, 0.7185, 0.7807]])
torch.Size([3, 3])


### Matrix multiplication

In [3]:
# Create a matrix of ones with shape 3 by 3
tensor_of_ones = torch.ones(3, 3)

# Create an identity matrix with shape 3 by 3
identity_tensor = torch.eye(3)

# Do a matrix multiplication of tensor_of_ones with identity_tensor
matrices_multiplied = torch.matmul(tensor_of_ones, identity_tensor)
print(matrices_multiplied)

# Do an element-wise multiplication of tensor_of_ones with identity_tensor
element_multiplication = tensor_of_ones * identity_tensor
print(element_multiplication)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


### Forward pass

In [4]:
# Initialize tensors x, y and z
x = torch.rand(1000, 1000)
y = torch.rand(1000, 1000)
z = torch.rand(1000, 1000)

# Multiply x with y
q = x * y

# Multiply elementwise z with q
f = z * q

mean_f = torch.mean(f)
print(mean_f)

tensor(0.1250)


### Backward Propagation using Pytorch

In [5]:
# Initialize x, y and z to values 4, -3 and 5
x = torch.tensor(4., requires_grad = True)
y = torch.tensor(-3.,  requires_grad = True)
z = torch.tensor(5.,  requires_grad = True)

# Set q to sum of x and y, set f to product of q with z
q = x + y
f = q * z

# Compute the derivatives
f.backward()

# Print the gradients
print("Gradient of x is: " + str(x.grad))
print("Gradient of y is: " + str(y.grad))
print("Gradient of z is: " + str(z.grad))

Gradient of x is: tensor(5.)
Gradient of y is: tensor(5.)
Gradient of z is: tensor(1.)


### Calculating gradients in PyTorch

In [6]:
# Multiply tensors x and y
q = x * y

# Elementwise multiply tensors z with q
f = z * q

mean_f = torch.mean(f)

# Calculate the gradients
mean_f.backward()

### Simple Neural Network

We are going to build a neural network in PyTorch, using the hard way. Our input will be images of size (28, 28), so images containing 784 pixels. Our network will contain an input_layer, a hidden layer with 200 units, and an output layer with 10 classes. 

In [7]:
# Initialize input_layer
input_layer = torch.rand(784)

# Initialize the weights of the neural network
weight_1 = torch.rand(784, 200)
weight_2 = torch.rand(200, 10)

# Multiply input_layer with weight_1
hidden_1 = torch.matmul(input_layer, weight_1)

# Multiply hidden_1 with weight_2
output_layer = torch.matmul(hidden_1, weight_2)
print(output_layer)

tensor([20450.7402, 20365.0098, 19188.5176, 19746.3652, 20923.8379, 19707.4316,
        20119.1406, 20167.5352, 20283.3301, 21185.0703])


### Pytorch Neural Network

In [16]:
from torch import nn

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        # Instantiate all 2 linear layers  
        self.fc1 = nn.Linear(784, 200)
        self.fc2 = nn.Linear(200, 10)

    def forward(self, x):
      
        # Use the instantiated layers and return x
        x = self.fc1(x)
        x = self.fc2(x)
        return x

input_layer = torch.rand(784)
net = Net()
result = net(input_layer)
result

tensor([-0.2372,  0.0713,  0.1923,  0.1003,  0.2090,  0.1629, -0.0249, -0.1947,
         0.1953, -0.0455], grad_fn=<AddBackward0>)