# Import Library

In [1]:
import tensorflow as tf

# How to Create a Tensor

## 1. Constant Tensor

### A. tf.constant()

In [2]:
#membuat nilai konstanta menggunakan TensorFlow
const_a = tf.constant([1,2,3,4], shape=[2,2], dtype=tf.float32)

#Print Nilai konstanta TensorFlow
const_a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

### B. tf.zeros()

In [3]:
#Penggunaan tf.zeros
zeros_b = tf.zeros(shape=[2, 3], dtype=tf.int32)

#Pengecekan nilai constant
zeros_b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

### C. tf.fill()

In [4]:
#penggunaan tf.fill()
fill_d = tf.fill([3,3], 8)

#Pengecekan nilai constant
fill_d

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])>

### D. tf.random()

###### shape: A 1-D integer Tensor or Python array. The shape of the output tensor.
###### mean: A Tensor or Python value of type dtype, broadcastable with stddev. The mean of the normal distribution.
###### stddev: A Tensor or Python value of type dtype, broadcastable with mean. The standard deviation of the normal distribution.
###### dtype: The type of the output.
###### seed: 	A Python integer. Used to create a random seed for the distribution. See tf.random.set_seed for behavior.
###### name: A name for the operation (optional).


In [5]:
#penggunaan tf.random.normal()
random_e = tf.random.normal([3,3],mean=0.0,stddev=1.0)

#Pengecekan nilai constant
random_e

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-2.3695185 , -1.5576515 , -0.03796951],
       [-0.16169445,  0.3917277 , -1.3685622 ],
       [ 1.2888266 , -0.67399544, -0.01773659]], dtype=float32)>

### E. tf.convert_to_tensor

###### value: An object whose type has a registered Tensor conversion function.
###### dtype: Optional element type for the returned tensor. If missing, the type is inferred from the type of value.
###### dtype_hint: Optional element type for the returned tensor, used when dtype is None. In some cases, a caller may not have a dtype in mind when converting to a tensor, so dtype_hint can be used as a soft preference. If the conversion to dtype_hint is not possible, this argument has no effect.
###### Name:	Optional name to use if a new Tensor is created.

In [6]:
#Pembuatan list untuk dimasukkan kedalam Tensor
list_f = [[1,2,3,4,5,6],[1,2,3,4,5,6]]

#Penggunaan tf.convert_to_tensor
tensor_f = tf.convert_to_tensor(list_f, dtype=tf.float32)

#Pengecekan nilai constant
tensor_f

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.]], dtype=float32)>

## 2. Variable Tensor

In [7]:
#Penggunaan tf.Variable
var_1 = tf.Variable(tf.ones([2,3]))

#Output dari tf.Variable
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [8]:
#nilai dari var_1 Sebelum diubah
print("Nilai dari var_1:",var_1.read_value())

Nilai dari var_1: tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [9]:
#nilai dari var_1 setelah di assign
var_value_1=[[1,2,3],[4,5,6]]
var_1.assign(var_value_1)
print("Nilai dari var_1 Setelah di assign:",var_1.read_value())



Nilai dari var_1 Setelah di assign: tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [10]:
#nilia var_1 setelah di beri addition_add(ditambah dengan nilai yg ada)
var_1.assign_add(tf.ones([2,3]))
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 3., 4.],
       [5., 6., 7.]], dtype=float32)>

# Tensor Slicing and Indexing

## 1. Slicing

In [11]:
print("Create a 4-dimensional tensor. The tensor contains four images. The size of each image is 100 x 100 x 3.")
tensor_i = tf.random.normal([2,3,3,3])
print(tensor_i)

Create a 4-dimensional tensor. The tensor contains four images. The size of each image is 100 x 100 x 3.
tf.Tensor(
[[[[ 1.3149329e-01 -3.7449169e-01 -6.1889148e-01]
   [-1.6083885e-02  8.4681076e-01  2.0880432e-01]
   [-3.8877577e-01 -1.5049698e+00 -9.2950350e-01]]

  [[ 1.3500657e-03  2.0713738e-01  4.9072751e-01]
   [-1.5424579e+00  4.1676688e-01 -4.7187513e-01]
   [-1.4158642e+00  1.4068052e+00  1.2959554e+00]]

  [[ 7.7605581e-01  2.6385847e-01 -1.5623240e+00]
   [ 2.2505672e-01 -9.3854660e-01  9.9304867e-01]
   [ 3.7833184e-01 -9.6847343e-01 -1.2843992e-01]]]


 [[[ 3.4343311e-01  1.1079037e+00  1.1948577e+00]
   [-3.6530188e-01  1.1144372e+00  3.4119806e-01]
   [-4.9470454e-01  1.0533648e+00 -1.1478168e+00]]

  [[-8.6156428e-01 -2.3840198e-01  1.0093477e-01]
   [-8.9816350e-01  9.0663320e-01 -1.1828864e+00]
   [-5.2452438e-02  5.7473642e-01  1.3670043e+00]]

  [[ 1.3501527e+00  1.2727159e+00 -1.8395348e+00]
   [-1.7487348e+00  1.0122824e+00 -8.7763751e-01]
   [-1.0161060e+00 -6.

In [12]:
#Ngambil data menggunakan index seperti biasa
print("\n Extract the first image.")
print(tensor_i[0,...])


 Extract the first image.
tf.Tensor(
[[[ 1.3149329e-01 -3.7449169e-01 -6.1889148e-01]
  [-1.6083885e-02  8.4681076e-01  2.0880432e-01]
  [-3.8877577e-01 -1.5049698e+00 -9.2950350e-01]]

 [[ 1.3500657e-03  2.0713738e-01  4.9072751e-01]
  [-1.5424579e+00  4.1676688e-01 -4.7187513e-01]
  [-1.4158642e+00  1.4068052e+00  1.2959554e+00]]

 [[ 7.7605581e-01  2.6385847e-01 -1.5623240e+00]
  [ 2.2505672e-01 -9.3854660e-01  9.9304867e-01]
  [ 3.7833184e-01 -9.6847343e-01 -1.2843992e-01]]], shape=(3, 3, 3), dtype=float32)


In [13]:
#Ngambil data menggunakan sistem interval(dimulai dari) dan mencontohkan penggunaan '...'
print("\n Extract one slice at an interval of two images.")
print(tensor_i[::1,...])


 Extract one slice at an interval of two images.
tf.Tensor(
[[[[ 1.3149329e-01 -3.7449169e-01 -6.1889148e-01]
   [-1.6083885e-02  8.4681076e-01  2.0880432e-01]
   [-3.8877577e-01 -1.5049698e+00 -9.2950350e-01]]

  [[ 1.3500657e-03  2.0713738e-01  4.9072751e-01]
   [-1.5424579e+00  4.1676688e-01 -4.7187513e-01]
   [-1.4158642e+00  1.4068052e+00  1.2959554e+00]]

  [[ 7.7605581e-01  2.6385847e-01 -1.5623240e+00]
   [ 2.2505672e-01 -9.3854660e-01  9.9304867e-01]
   [ 3.7833184e-01 -9.6847343e-01 -1.2843992e-01]]]


 [[[ 3.4343311e-01  1.1079037e+00  1.1948577e+00]
   [-3.6530188e-01  1.1144372e+00  3.4119806e-01]
   [-4.9470454e-01  1.0533648e+00 -1.1478168e+00]]

  [[-8.6156428e-01 -2.3840198e-01  1.0093477e-01]
   [-8.9816350e-01  9.0663320e-01 -1.1828864e+00]
   [-5.2452438e-02  5.7473642e-01  1.3670043e+00]]

  [[ 1.3501527e+00  1.2727159e+00 -1.8395348e+00]
   [-1.7487348e+00  1.0122824e+00 -8.7763751e-01]
   [-1.0161060e+00 -6.9479650e-01  8.3734286e-01]]]], shape=(2, 3, 3, 3), dty

In [14]:
#Mengambil Data Dari belakang
print("\n Slice data from the last element.")
print(tensor_i[::-1])


 Slice data from the last element.
tf.Tensor(
[[[[ 3.4343311e-01  1.1079037e+00  1.1948577e+00]
   [-3.6530188e-01  1.1144372e+00  3.4119806e-01]
   [-4.9470454e-01  1.0533648e+00 -1.1478168e+00]]

  [[-8.6156428e-01 -2.3840198e-01  1.0093477e-01]
   [-8.9816350e-01  9.0663320e-01 -1.1828864e+00]
   [-5.2452438e-02  5.7473642e-01  1.3670043e+00]]

  [[ 1.3501527e+00  1.2727159e+00 -1.8395348e+00]
   [-1.7487348e+00  1.0122824e+00 -8.7763751e-01]
   [-1.0161060e+00 -6.9479650e-01  8.3734286e-01]]]


 [[[ 1.3149329e-01 -3.7449169e-01 -6.1889148e-01]
   [-1.6083885e-02  8.4681076e-01  2.0880432e-01]
   [-3.8877577e-01 -1.5049698e+00 -9.2950350e-01]]

  [[ 1.3500657e-03  2.0713738e-01  4.9072751e-01]
   [-1.5424579e+00  4.1676688e-01 -4.7187513e-01]
   [-1.4158642e+00  1.4068052e+00  1.2959554e+00]]

  [[ 7.7605581e-01  2.6385847e-01 -1.5623240e+00]
   [ 2.2505672e-01 -9.3854660e-01  9.9304867e-01]
   [ 3.7833184e-01 -9.6847343e-01 -1.2843992e-01]]]], shape=(2, 3, 3, 3), dtype=float32)


## 2. Indexing

### A. tf.gather()

In [17]:
#Extract the first, second, and fourth images from tensor_i ([2,2,2,3]).
indices = [0,1,3]
tf.gather(tensor_i,axis=0,indices=indices)

InvalidArgumentError: indices[2] = 3 is not in [0, 2) [Op:GatherV2]

### B. tf.gather_nd

In [18]:
# Mengambil nilai piksel [,] dari dimensi pertama gamabr pertama dan piksek [,] dari dimensi pertama dan gamabr kedua pada tensor_i
indices = [[0,1,1,0],[1,2,2,0]]
tf.gather_nd(tensor_i,indices=indices)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1.5424579, -1.016106 ], dtype=float32)>

# Tensor Dimension Modification

## 1. Dimension Display

In [19]:
# Pembuatan Tensor
const_d_1 = tf.constant([[1, 2, 3, 4]],shape=[2,2], dtype=tf.float32)


In [20]:
#Common display dimension
const_d_1.shape

TensorShape([2, 2])

In [21]:
#Common display dimension
const_d_1.get_shape()

TensorShape([2, 2])

In [22]:
#Common display dimension
tf.shape(const_d_1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2])>

## 2. Dimension Reshaping

In [23]:
#Before Reshaping
reshape_1 = tf.constant([[1,2,3],[4,5,6]])
reshape_1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [24]:
#After Reshaping
tf.reshape(reshape_1, (3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

## 3. Dimension Expansion

In [25]:
#Generate a 100 x 100 x 3 tensor to represent a 100 x 100 three-channel color image.
expand_sample_1 = tf.random.normal([100,100,3], seed=1)

print("size of the original data:",expand_sample_1.shape)

size of the original data: (100, 100, 3)


In [26]:
print("add a dimension before the first dimension (axis = 0): ",tf.expand_dims(expand_sample_1, axis=0).shape)

add a dimension before the first dimension (axis = 0):  (1, 100, 100, 3)


In [27]:
print("add a dimension before the second dimension (axis = 1): ",tf.expand_dims(expand_sample_1, axis=1).shape)

add a dimension before the second dimension (axis = 1):  (100, 1, 100, 3)


In [28]:
print("add a dimension after the last dimension (axis = –1): ",tf.expand_dims(expand_sample_1, axis=-1).shape)

add a dimension after the last dimension (axis = –1):  (100, 100, 3, 1)


## 4. Dimension Squeezing

In [29]:
#Generate a 100 x 100 x 3 tensor to represent a 100 x 100 three-channel color image.
squeeze_sample_1 = tf.random.normal([1,100,100,3])

print("size of the original data:",squeeze_sample_1.shape)

size of the original data: (1, 100, 100, 3)


In [30]:
squeezed_sample_1 = tf.squeeze(squeeze_sample_1)

print("data size after dimension squeezing:",squeezed_sample_1.shape)

data size after dimension squeezing: (100, 100, 3)


## 5. Transpose

In [31]:
#Input the tensor to be transposed, and call tf.transpose.
trans_sample_1 = tf.constant([1,2,3,4,5,6],shape=[2,3])

print("size of the original data:",trans_sample_1.shape)

size of the original data: (2, 3)


In [32]:
transposed_sample_1 = tf.transpose(trans_sample_1)

print("size of transposed data:",transposed_sample_1.shape)

size of transposed data: (3, 2)


## 6. Broadcast

In [33]:
broadcast_sample_1 = tf.constant([1,2,3,4,5,6])

print("original data:",broadcast_sample_1)

original data: tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [34]:
broadcasted_sample_1 = tf.broadcast_to(broadcast_sample_1,shape=[4,6])

print("broadcasted data:",broadcasted_sample_1)

broadcasted data: tf.Tensor(
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]], shape=(4, 6), dtype=int32)


# Arithmetic Operations on Tensors

## 1. Arithmetic Operator

In [35]:
a = tf.constant([[3, 5], [4, 8]])
b = tf.constant([[1, 6], [2, 9]])

print("Hasil dari Penjumlahan adalah:\n",tf.add(a, b))

Hasil dari Penjumlahan adalah:
 tf.Tensor(
[[ 4 11]
 [ 6 17]], shape=(2, 2), dtype=int32)


## 2. Matrix Multiplication

In [36]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 63],
       [20, 96]])>

## 3. Tensor Statistics Collection

In [37]:
argmax_sample_1 = tf.constant([[1,3,2],[2,5,8],[7,5,9]])
print("input tensor:",argmax_sample_1.numpy())

input tensor: [[1 3 2]
 [2 5 8]
 [7 5 9]]


In [38]:
max_sample_1 = tf.argmax(argmax_sample_1, axis=0)
print("locate the maximum value by column:",max_sample_1.numpy())

locate the maximum value by column: [2 1 2]


In [39]:
max_sample_2 = tf.argmax(argmax_sample_1, axis=1)
print("locate the maximum value by row:",max_sample_2.numpy())

locate the maximum value by row: [1 2 2]


# Dimension-based Arithmetic Operations

##### input_tensor: Tensor yang akan dikurangi. Harus memiliki tipe numeric 
##### axis: Dimensi yang akan dikurangi
##### keepdims: jika bernilai True, mempertahankan dimensi yang dikurangi dengan panjang 1

In [40]:
reduce_sample_1 = tf.constant([1,2,3,4,5,6],shape=[2,3])
print("original data",reduce_sample_1.numpy())

original data [[1 2 3]
 [4 5 6]]


In [41]:
print("calculate the sum of all elements in the tensor (axis = None): ",tf.reduce_sum(reduce_sample_1,axis=None).numpy())

calculate the sum of all elements in the tensor (axis = None):  21


In [42]:
print("calculate the sum of elements in each column by column (axis = 0): ",tf.reduce_sum(reduce_sample_1,axis=0).numpy())

calculate the sum of elements in each column by column (axis = 0):  [5 7 9]


In [43]:
print("calculate the sum of elements in each column by row (axis = 1): ",tf.reduce_sum(reduce_sample_1,axis=1).numpy())

calculate the sum of elements in each column by row (axis = 1):  [ 6 15]


# Tensor Concatenation and SPlitting

## 1. Tensor Concatenation

### A. tf.contact()

In [62]:
concat_sample_1 = tf.random.normal([4,100,100,3])
concat_sample_2 = tf.random.normal([40,100,100,3])

print("sizes of the original data:",concat_sample_1.shape,concat_sample_2.shape)

sizes of the original data: (4, 100, 100, 3) (40, 100, 100, 3)


In [63]:
concated_sample_1 = tf.concat([concat_sample_1,concat_sample_2],axis=0)
print("size of the concatenated data:",concated_sample_1.shape)

size of the concatenated data: (44, 100, 100, 3)


### B. tf.stack()

In [46]:
stack_sample_1 = tf.random.normal([100,100,3])
stack_sample_2 = tf.random.normal([100,100,3])

print("sizes of the original data: ",stack_sample_1.shape, stack_sample_2.shape)

sizes of the original data:  (100, 100, 3) (100, 100, 3)


In [47]:
#Dimensions increase after the concatenation. If axis is set to 0, a dimension is added before the first dimension.
stacked_sample_1 = tf.stack([stack_sample_1, stack_sample_2],axis=0)
print("size of the concatenated data:",stacked_sample_1.shape)

size of the concatenated data: (2, 100, 100, 3)


## 2. Tensor Splitting

### A. tf.unstack()

In [64]:
stacked_sample_1

<tf.Tensor: shape=(2, 100, 100, 3), dtype=float32, numpy=
array([[[[ 1.5067011 ,  1.2816238 , -1.4268799 ],
         [-1.2571189 ,  2.1674824 , -1.6251478 ],
         [ 0.52987385, -0.49626285,  1.3429546 ],
         ...,
         [ 0.5615166 ,  0.50560397, -0.1383535 ],
         [ 0.3788111 ,  0.7402054 ,  0.19789618],
         [-0.29981023,  0.17557143, -0.17000885]],

        [[ 0.24297644,  1.7907987 , -0.8376696 ],
         [ 0.10100961, -0.40576032,  0.96147454],
         [-0.19724175, -2.564001  ,  0.05865294],
         ...,
         [-2.3683643 ,  0.45723787,  0.39071387],
         [ 1.0510348 , -1.3000565 , -1.763876  ],
         [ 0.30565348,  0.42300174,  0.8311379 ]],

        [[-1.4235442 ,  0.92886174,  1.507868  ],
         [-0.29531384, -0.05153668,  0.07721885],
         [ 0.06416343, -0.32228103, -0.9540612 ],
         ...,
         [-0.38686118, -0.09961329,  0.3583177 ],
         [-0.5607858 , -0.3439029 ,  1.7155246 ],
         [ 2.0804176 , -0.6421268 , -0.7249232

In [48]:
#Split data based on the first dimension and output the split data in a list.
tf.unstack(stacked_sample_1)

[<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
 array([[[ 1.5067011 ,  1.2816238 , -1.4268799 ],
         [-1.2571189 ,  2.1674824 , -1.6251478 ],
         [ 0.52987385, -0.49626285,  1.3429546 ],
         ...,
         [ 0.5615166 ,  0.50560397, -0.1383535 ],
         [ 0.3788111 ,  0.7402054 ,  0.19789618],
         [-0.29981023,  0.17557143, -0.17000885]],
 
        [[ 0.24297644,  1.7907987 , -0.8376696 ],
         [ 0.10100961, -0.40576032,  0.96147454],
         [-0.19724175, -2.564001  ,  0.05865294],
         ...,
         [-2.3683643 ,  0.45723787,  0.39071387],
         [ 1.0510348 , -1.3000565 , -1.763876  ],
         [ 0.30565348,  0.42300174,  0.8311379 ]],
 
        [[-1.4235442 ,  0.92886174,  1.507868  ],
         [-0.29531384, -0.05153668,  0.07721885],
         [ 0.06416343, -0.32228103, -0.9540612 ],
         ...,
         [-0.38686118, -0.09961329,  0.3583177 ],
         [-0.5607858 , -0.3439029 ,  1.7155246 ],
         [ 2.0804176 , -0.6421268 , -0.7249232

### B. tf.split()

tf.split(value, num_or_size_splits, axis=0, num=None, name='split'):
    - value: The Tensor to split.
    - num_or_size_splits:	Either an integer indicating the number of splits along axis or a 1-D integer Tensor or Python list containing the sizes of each output tensor along axis. If a scalar, then it must evenly divide value.shape[axis]; otherwise the sum of sizes along the split axis must match that of the value.
    - axis: An integer or scalar int32 Tensor. The dimension along which to split. Must be in the range [-rank(value), rank(value)). Defaults to 0.
    - num: Optional, used to specify the number of outputs when it cannot be inferred from the shape of size_splits.
    - name:	A name for the operation (optional).
tf.split() splits a tensor in either of the following ways:
    - If the value of num_or_size_splits is an integer, the tensor is evenly split into sub tensors in the specified dimension (axis = D).
    - If the value of num_or_size_splits is a vector, the tensor is split into sub tensors based on the element value of the vector in the specified dimension (axis = D).


In [49]:
import numpy as np
split_sample_1 = tf.random.normal([10,100,100,3])
print("size of the original data:",split_sample_1.shape)

size of the original data: (10, 100, 100, 3)


In [50]:
splited_sample_1 = tf.split(split_sample_1, num_or_size_splits=5,axis=0)
print("size of the split data when m_or_size_splits is set to 10: ",np.shape(splited_sample_1))

size of the split data when m_or_size_splits is set to 10:  (5, 2, 100, 100, 3)


In [51]:
splited_sample_2 = tf.split(split_sample_1, num_or_size_splits=[3,5,2],axis=0)
print("sizes of the split data when num_or_size_splits is set to [3,5,2]:",
np.shape(splited_sample_2[0]),
np.shape(splited_sample_2[1]),
np.shape(splited_sample_2[2]))

sizes of the split data when num_or_size_splits is set to [3,5,2]: (3, 100, 100, 3) (5, 100, 100, 3) (2, 100, 100, 3)


# Tensor Sorting Methods

## 1. tf.sort() & tf.argsort()

In [52]:
sort_sample_1 = tf.random.shuffle(tf.range(10))
print("input tensor:",sort_sample_1.numpy())

input tensor: [7 2 8 5 1 0 6 4 3 9]


In [53]:
sorted_sample_1 = tf.sort(sort_sample_1, direction="ASCENDING")
print("tensor sorted in ascending order:",sorted_sample_1.numpy())

tensor sorted in ascending order: [0 1 2 3 4 5 6 7 8 9]


In [54]:
sorted_sample_2 = tf.argsort(sort_sample_1,direction="ASCENDING")
print("indexes of elements in ascending order:",sorted_sample_2.numpy())

indexes of elements in ascending order: [5 4 1 8 7 3 6 0 2 9]


## 2. tf.nn.tpp_k()

In [55]:
values, index = tf.nn.top_k(sort_sample_1,5)
print("input tensor:",sort_sample_1.numpy())

input tensor: [7 2 8 5 1 0 6 4 3 9]


In [56]:
print("first five values in ascending order:", values.numpy())

first five values in ascending order: [9 8 7 6 5]


In [57]:
print("indexes of the first five values in ascending order:", index.numpy())

indexes of the first five values in ascending order: [9 2 0 6 3]


# Eager Execution

In [58]:
#Use the syntax of TensorFlow 1.x in TensorFlow 2.x. You can install the v1 compatibility package in TensorFlow 2.0 to inherit the TensorFlow 1.x code and disable the eager execution mode.
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
#Create a graph and define it as a computational graph.
a = tf.ones((2, 2), dtype=tf.dtypes.float32)
b = tf.constant([[1, 2],
[3, 4]], dtype=tf.dtypes.float32)
c = tf.matmul(a, b)
#Enable the drawing function, and perform the multiplication operation to obtain data.
with tf.Session() as sess:
    print(sess.run(c))

[[4. 6.]
 [4. 6.]]


In [59]:
import tensorflow as tf
thre_1 = tf.random.uniform([], 0, 1)
x = tf.reshape(tf.range(0, 4), [2, 2])
print(thre_1)
if thre_1.numpy() > 0.5:
y = tf.matmul(x, x)
else:
y = tf.add(x, x)

IndentationError: expected an indented block (Temp/ipykernel_18360/1524455116.py, line 6)

# AutoGraph of TensorFlow 2.x

In [ ]:
@tf.function
def simple_nn_layer(w,x,b):
    print(b)
    return tf.nn.relu(tf.matmul(w, x)+b)
    
w = tf.random.uniform((3, 3))
x = tf.random.uniform((3, 3))
b = tf.constant(0.5, dtype='float32')
simple_nn_layer(w,x,b)

Tensor("b:0", shape=(), dtype=float32)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1.1920661 , 1.191967  , 1.2391963 ],
       [1.4967974 , 1.1712788 , 1.279865  ],
       [0.86344826, 0.63646233, 0.7125404 ]], dtype=float32)>

In [ ]:
#Use the timeit module to measure the execution time of a small code segment.
import timeit

#Create a convolutional layer.
CNN_cell = tf.keras.layers.Conv2D(filters=100,kernel_size=2,strides=(1,1))

In [ ]:
#Use @tf.function to convert the operation into a graph.
@tf.function
def CNN_fn(image):
    return CNN_cell(image)

image = tf.zeros([100, 200, 200, 3])

In [ ]:
#Compare the execution time of the two modes.
CNN_cell(image)
CNN_fn(image)

<tf.Tensor: shape=(100, 199, 199, 100), dtype=float32, numpy=
array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., 

In [ ]:
#Call timeit.timeit to measure the time required for executing the code 10 times.
print("Computation of one CNN layer in eager execution mode:", timeit.timeit(lambda: CNN_cell(image), number=10))
print("Computation of one CNN layer in graph mode:", timeit.timeit(lambda: CNN_fn(image), number=10))

Computation of one CNN layer in eager execution mode: 7.033313199994154
Computation of one CNN layer in graph mode: 3.6503439999651164
